# Generated by Django 4.0 on 2022-01-18 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('learning_logs', '0002_topic_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='Headline',
        ),
        migrations.RenameModel(
            old_name='Entry',
            new_name='Post',
        ),
    ]
